// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsqKTYzi0t7VdPe7rjxIbHvHJvk4_fh1c',
    appId: '1:792990131550:web:e5d094fbc659a6d5769bcf',
    messagingSenderId: '792990131550',
    projectId: 'edugalaxy-app',
    authDomain: 'edugalaxy-app.firebaseapp.com',
    storageBucket: 'edugalaxy-app.firebasestorage.app',
    measurementId: 'G-J9JZPG3XM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn6YfoLHJGrs380-yyNdIiG-dM1eyQDEM',
    appId: '1:792990131550:android:a1cb0201b8f27723769bcf',
    messagingSenderId: '792990131550',
    projectId: 'edugalaxy-app',
    storageBucket: 'edugalaxy-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw1psWdBJwUTifl__y48kFlVodeUcQkP0',
    appId: '1:792990131550:ios:f7a13557fe865162769bcf',
    messagingSenderId: '792990131550',
    projectId: 'edugalaxy-app',
    storageBucket: 'edugalaxy-app.firebasestorage.app',
    iosBundleId: 'com.example.myFistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw1psWdBJwUTifl__y48kFlVodeUcQkP0',
    appId: '1:792990131550:ios:f7a13557fe865162769bcf',
    messagingSenderId: '792990131550',
    projectId: 'edugalaxy-app',
    storageBucket: 'edugalaxy-app.firebasestorage.app',
    iosBundleId: 'com.example.myFistApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsqKTYzi0t7VdPe7rjxIbHvHJvk4_fh1c',
    appId: '1:792990131550:web:7c85b073f0c0d38b769bcf',
    messagingSenderId: '792990131550',
    projectId: 'edugalaxy-app',
    authDomain: 'edugalaxy-app.firebaseapp.com',
    storageBucket: 'edugalaxy-app.firebasestorage.app',
    measurementId: 'G-JE4J71PPML',
  );
}
